flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField, SubmitField, TextAreaField
from flask_blog.models import Post

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_blog/summarize/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, ValidationError
from wtforms import SubmitField, TextAreaField


class SummarizeForm(FlaskForm):
    full_text = TextAreaField('Long text', validators=[DataRequired()])
    summary = TextAreaField('Summary', render_kw={"cols":35, "rows":12})
    submit = SubmitField('Summarize')

    def validate_text_length(self, full_text):
        """Ensures the user's text input is long enough to generate a strong summary. """

        if len(full_text) < 1000:
            raise ValidationError(
                "Text is not long enough to generate a summary.")

flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post

main = Blueprint('main', __name__)

@main.route('/') # create home route. Browser will display whatever is returned from the following function
@main.route('/home') # make it so / and /home go to the same place
def home():
    """This route is the home/default landing page for website and can be accessed with '/' or '/home' """
    page = request.args.get('page', 1, type=int)
    # Show 5 posts per page, ordered by date posted
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts) # we can now access this variable in the template using arg name 'posts'

@main.route('/about')
def about():
    return render_template('about.html', title='About', legend_name="Elliot's Website")

flask_blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """This route is where users will add new posts to the blog."""
    form = PostForm()
    if form.validate_on_submit():
        # create instance of Post class w/ this post's content. I could have expressed the 'user_id=current_user' attribute as 'author=current_user' instead, since it's backref to class User.
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend_name='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    # grab the post from the db. If it doesn't exist, return 404 error ('page doesn't exist')
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """This route is where users can modify their existing posts """
    # grab the post from the db. If it doesn't exist, return 404 error ('page doesn't exist')
    post = Post.query.get_or_404(post_id)
    # Ensure the editor is actually the author of the post
    if post.author != current_user:
        abort(403)  # 403 is HTTP response for a forbidden route.
    form = PostForm()
    # If it's a POST request (meaning user submitted the form), update DB if the changes are valid.
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    # Otherwise (GET request), pre-populate form with existing post data
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend_name='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    """This route allows users to delete posts """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

flask_blog/summarize/routes.py
from flask import render_template, flash, Blueprint
from flask_blog.summarize.forms import SummarizeForm
from flask_blog.summarize.utils import summarize_text

summarize = Blueprint('summarize', __name__)


@summarize.route('/summarize-text', methods=['GET', 'POST'])
def magic_summarize():
    """ This route allows users to get a summarized version of any long text (such as an article or email). """

    form = SummarizeForm()

    if form.validate_on_submit():
        full_text = form.full_text.data
        summary = summarize_text(full_text)
        form.summary.data = summary
        return render_template('summarize.html', form=form, title='Summarize Text', summary=summary, legend_name="Summarize Text")

    return render_template('summarize.html', form=form, title='Summarize Text', legend_name="Summarize Text")

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm)
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    """This route is where users register for an account."""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit(): # if the form was valid when it was submitted:
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    """This route is where users login"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Check if user exists & the password is valid. If so, login. Otherwise, flash error.
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email & password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """This route is where users can update their username, email address, and profile picture."""
    form = UpdateAccountForm()
    # Run validations for the form and if the new username/email is valid, update the DB with the new user info.
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    # if this is a GET request (meaning browser is just pulling the form, not submitting), auto-populate the fields with the user's existing info
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) # DB call
    # Also return image_file so we can reference that in our template
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    """This route shows all posts for a given user. """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404() # if the username isn't associated with any posts, return 404 error
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user) # we can now access this variable in the template using arg name 'posts'

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    """This is the first reset_password route that only asks user for email & verifies. """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    """This route is where users actually reset their password.  """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token) # returns user ID associated with the token
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit(): # if the form was valid when it was submitted:
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flask_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4">{{ legend_name }}</legend>
    <p>Welcome to my first website, powered by Flask. Feel free to<a class="ml-2"
            href="{{ url_for('users.register') }}">create an account</a> (if you haven't already) and write a post to
        let me know what you think!</p>
    <ul>- Elliot</ul>
</div>
{% endblock content %}

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src={{ image_file }}>
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
        <!-- open a form tag with post, so that it posts the info to the same form we're currently on (don't forget encoding type!!!) -->
        <form method="POST" action="" enctype="multipart/form-data">
          <!-- enter form fields: hidden tag, then  -->
          {{ form.hidden_tag() }} <!-- adds a token that interfaces w/ secret key to protect the website, don't worry about the rest but we do need this -->
          <!-- We will add some html/css classes here from bootstrap for asthetics -->
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <!-- Now we start adding our fields -->
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}
              <!-- Check for errors! This part is what highlights to the user what was wrong with their input. Use for all fields w/ validation. -->
              {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                    <span> {{ error }} </span>
                  {% endfor %}
                </div>
              <!-- What to do if there are no errors -->
              {% else %}
                {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span> {{ error }} </span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.picture.label() }}
              {{ form.picture(class="form-control-file") }}
              {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                  <span class="text-danger"> {{ error }} </span></br>
                {% endfor %}
              {% endif %}
          </fieldset>
          <!-- Now we design our submit button field -->
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
  </div>
{% endblock content %}

flask_blog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <!-- open a form tag with post, so that it posts the info to the same form we're currently on  -->
  <form method="POST" action="">
    <!-- enter form fields: hidden tag, then  -->
    {{ form.hidden_tag() }}
    <!-- adds a token that interfaces w/ secret key to protect the website, don't worry about the rest but we do need this -->
    <!-- We will add some html/css classes here from bootstrap for asthetics -->
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend_name }}</legend>
      <!-- Now we start adding our fields -->
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span> {{ error }} </span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
        {{ form.content(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span> {{ error }} </span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

flask_blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <!-- Display posts -->
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%m/%d/%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <!-- Add page navigator where users can select which page they'd like to see (limiting number of buttons displayed) -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      <!-- If there is content on the page, display a button to go to that page-->
      {% if page_num %}
        <!-- Different button style (filled-in) for the page that we're currently on -->
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
  <title>Elliot's Flask Blog - {{ title }}</title>
  {% else %}
  <title>Elliot's Flask Blog</title>
  {% endif %}
</head>
<!-- Navigation Bar Setup -->

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <!-- Navbar left side -->
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Elliot's Flask Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('summarize.magic_summarize') }}">Paraphrase</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <!-- Display 'login' & 'register' if no one logged in, 'logout' otherwise -->
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        <!-- Flash any alerts (if necessary) -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
          {% endfor %}
          {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div> <!-- End flash section -->
        <div class="col-md-4">
          <div class="content-section">
            <h3>Blog</h3>
            <p class='text-muted'>View our latest posts, announcements, and more!
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Coming soon...</li>
              <li class="list-group-item list-group-item-light">Coming soon...</li>
              <li class="list-group-item list-group-item-light">Coming soon...</li>
              <li class="list-group-item list-group-item-light">Coming soon...</li>
            </ul>
            </p>
          </div>
        </div>
      </div>
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
      <!-- open a form tag with post, so that it posts the info to the same form we're currently on  -->
      <form method="POST" action="">
        <!-- enter form fields: hidden tag, then  -->
        {{ form.hidden_tag() }} <!-- adds a token that interfaces w/ secret key to protect the website, don't worry about the rest but we do need this -->
        <!-- We will add some html/css classes here from bootstrap for asthetics -->
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Log In</legend>
          <!-- Now we start adding our fields -->
            <!-- What to do if there are no errors -->
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span> {{ error }} </span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <!-- Remember Me checkbox -->
          <div class="form-check">
            {{ form.remember(class="form-check-input")}}
            {{ form.remember.label(class="form-check-label")}}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
          <small class="text-muted ml-2">
            <a href="{{ url_for('users.reset_request')}}">Forgot Password?</a>
          </small>
        </div>

      </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Don't have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
    </small>
  </div>

{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%m/%d/%Y') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
            <!-- Trigger Modal: If user deletes post, modal appears asking 'are you sure?' -->
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"f>Delete</button>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flask_blog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
      <!-- open a form tag with post, so that it posts the info to the same form we're currently on  -->
      <form method="POST" action="">
        <!-- enter form fields: hidden tag, then  -->
        {{ form.hidden_tag() }} <!-- adds a token that interfaces w/ secret key to protect the website, don't worry about the rest but we do need this -->
        <!-- We will add some html/css classes here from bootstrap for asthetics -->
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Reset Password</legend>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span> {{ error }} </span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
  </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <!-- Display posts for specific user -->
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%m/%d/%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <!-- Add page navigator where users can select which page they'd like to see (limiting number of buttons displayed) -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      <!-- If there is content on the page, display a button to go to that page-->
      {% if page_num %}
        <!-- Different button style (filled-in) for the page that we're currently on -->
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}